### ISSUE TITLE
About BFM.mat

### ISSUE THREAD

**Issue by junyizeng** [jinyugy21/Adv-Stickers_RHDE#2]
Thank you very much for open sourcing this work, there are multiple download paths in the BFM get page you provided, which one did you use to download?
![KO J@M$GZ}1}BS87 C}DNQJ](https://user-images.githubusercontent.com/80525097/211143486-8996e9ac-ad34-4384-a7b3-c78bf2aabb0f.png)

**Comment by junyizeng** [comment]
I seem to have found the correct BFM file, thanks again for the open source！

**Comment by jinyugy21** [comment]
> I seem to have found the correct BFM file, thanks again for the open source！

If still needed, our BFM can be downloaded from the link below:
https://drive.google.com/file/d/1sTNEi7MGMe-azOkAtc5bg6QuEwFI1XvT/view?usp=share_link
